### ISSUE TITLE
Graphs not showing up

### ISSUE THREAD

**Issue by Nickchapman3773** [matthayes/anki_progress_stats#21]
Hey, 

I recently got a new PC and downloaded 2.1 (always used 2.0 previously). All of my other addons work, but this addon will not show the graphs in the stats section. It previously worked for me on my old computer, and still does not work after deactivation of every other addon. Any thoughts?

**Comment by matthayes** [comment]
Thanks for the report.  I moved the charts higher in the page so that they're now between Answer Buttons and Card Types.  Do you see them there.  I just wanted to make sure you're not scrolling too fast past them and missing them.   Otherwise, can you share what version of Anki you're using?  I haven't had issues with the addon on 2.1 so far.  It's possible this is a Windows-specific issue.

**Comment by Nickchapman3773** [comment]
I do not see it between answer buttons and card types unfortunately.  I'm not sure how to tell what version of anki i'm using aside from the fact that it is 2.1 and I downloaded it about 3 days ago..  I'm also on the most updated version of windows 10.

**Comment by matthayes** [comment]
Okay thanks. I’ll try running this on Windows 10 with latest Anki and see if I can reproduce it.

**Comment by matthayes** [comment]
I tried reproducing this with the latest Anki (2.1.15) and Windows 10.  I am able to see the graphs for decks that have reviews.  However, if I select a deck that I haven't done any reviews for then I don't see the graphs.  This behavior was intentional but maybe it's confusing.  Could this be the issue you are having?  Can you try selecting another deck first before clicking Stats (assuming you have multiple) or selecting the `collection` radio button at the bottom to show stats across all decks?  The bottom of the stats screen tells you the scope for what the stats are computed over.

**Comment by Nickchapman3773** [comment]
I am trying to check stats for my overall parent deck. Does not work on parent deck, subdecks for which i did reviews, or when i hit collection.

**Comment by matthayes** [comment]
Hmm strange.  There are a couple ways we could debug this.  One is for you to export your deck with all the scheduling info (if you're comfortable with this).  I can import it and see if I can then reproduce the problem, in case it is an issue with the data.  If that doesn't reproduce the issue then it is something environmental with your Anki setup.  In that case I can create a version of the plugin with lots of logging so we have more visibility into what's going in.  I suspect that querying the database is yielding no data for some reason and as a result the graphs don't show up.  Are you willing to help me debug with either of these methods?

**Comment by Nickchapman3773** [comment]
Sure. I will export it to you. Where would you like it uploaded? Also, it will take me a couple of days, as I have a 24 hour shift today and a big exam on Friday, so sorry in advance for the delay :)

**Comment by matthayes** [comment]
Okay no problem.  Hope the exam went well ;)  You can upload to the link below.  Only I will be able to view it.  When you export choose `Anki Collection Package`.  You can uncheck `Include media`.

https://www.dropbox.com/request/Zd843hIVjwhJuNcmTB3a

If I can't repro with this then I'll make a special debugging version of the plugin.

**Comment by matthayes** [comment]
Hi again, just checking if you'll have time to share your deck with me so I can figure out your issue.  Thanks :)

**Comment by matthayes** [comment]
Hi @Nickchapman3773 just wanted to check once more if you can help provide some data so I can investigate.

**Comment by matthayes** [comment]
Closing this for now.  Please reopen if you have more information about the problem.
