### ISSUE TITLE
Cards Learned Not Working

### ISSUE THREAD

**Issue by 1burrito** [matthayes/anki_progress_stats#22]
Hello there,

I've been using your add-on for a while, and it has always worked flawlessly.  Since I transferred to 2.1, however, the "learned" graph has been showing inaccurate information.  In the example below I learned around 130 cards, and the graph shows that I learned just over 50.  I've tried deleting and re-downloading thus far.  Any ideas?

![image](https://user-images.githubusercontent.com/58489310/70089074-7605b100-15e5-11ea-839a-8c16ced07ef1.png)
![image](https://user-images.githubusercontent.com/58489310/70089164-9d5c7e00-15e5-11ea-9b56-f92b9783e5d3.png)

**Comment by matthayes** [comment]
Thanks for the report!  Can you explain how you determined the value of 130?  Also were these 130 cards all seen for the first time and completed review in the same day? (i.e. -1d in the chart)

If you're willing to share your deck with me that would help me diagnose the issue much faster.  You can export and upload at the link below.  Only I will have access to it.

https://www.dropbox.com/request/hu6iFzgnDuZsDogaVNX3

**Comment by 1burrito** [comment]
So I have a bunch of premade cards that I keep in the "combined review" deck I sent you that stay suspended.  When I'm ready to add more cards (like yesterday / -1d), I'll unsuspend them, move them to the "combined current" deck, and then do them.  Yesterday I did that process with around 130 cards, all seen for the first time and reviewed.

I uploaded both of those decks without media files (since they are huge), but let me know if you want them with media.  Thanks for the help!

**Comment by matthayes** [comment]
Thanks!  I will take a look later today and hopefully get some answers.  Stay tuned.

**Comment by matthayes** [comment]
I've done some investigation and have some information to share.

I performed a search `"deck:Combined Current" rated:2`(shows cards answered in last 2 days) in the browser, sorted by Due descending and then looked at cards due Dec 3, because presumably these are mostly cards you learned on Dec 2.  There are 129 such cards, so this matches pretty closely to the 130 new cards you said you reviewed.  If you right click on some of these cards and select Info you can see the review history.  Below are a few screenshots from these cards.

<img width="461" alt="Screen Shot 2019-12-03 at 10 21 12 PM" src="https://user-images.githubusercontent.com/212331/70118362-9c930e80-161c-11ea-9d29-74b2d838d6b9.png">

<img width="448" alt="Screen Shot 2019-12-03 at 10 21 46 PM" src="https://user-images.githubusercontent.com/212331/70118369-a157c280-161c-11ea-8356-f8559c50649b.png">

<img width="459" alt="Screen Shot 2019-12-03 at 10 22 36 PM" src="https://user-images.githubusercontent.com/212331/70118376-a4eb4980-161c-11ea-89c0-eb27631655d1.png">

Looking at the last screenshot, it appears you first saw the card on 3/27 and there were some reviews the following month.  Then on 12/2 for some reason the card's type goes back to Learn, as if the previous review history was ignored.  A similar pattern happens with the other cards.

This explains why these reviews are not showing up in the Learned Cards graph for `-1d`.  The plugin is designed to only count a card as learned when it was [learned for the first time](https://github.com/matthayes/anki_progress_stats/blob/master/progress_stats/compute.py#L208).  Because these cards appear to already be learned earlier in the year, they are not counted.  There are 56 cards learned on `-1d` that were learned for the first time.

By the way, here is what the graph would look like if I remove the restriction on being learned for the first time (`review.id == review.first_learned_id`).  In this graph a card is counted as learned anytime it exits the learning phase (which can happen after relearning a card when hitting Again too).

<img width="655" alt="Screen Shot 2019-12-03 at 10 26 08 PM" src="https://user-images.githubusercontent.com/212331/70118377-a87ed080-161c-11ea-839b-5bb5f14a8e97.png">

So, this explains why the graph looks the way it does based on the review history.  But I'm curious why the review history appears this way.  Can you think of any reason why on 12/2 the cards would be put back in to Learning?  Did anything noteworthy happen on 12/2?

One thought I just had is that it may be useful to have two different Learned Cards graphs.  In addition to the current graph that shows Learned Cards first seen there could also be a graph for Learned Cards seen whenever.  The latter basically counts how many cards were either learned for the first time or relearned.  This could make it less confusing when this scenario arises.  Thoughts?

**Comment by 1burrito** [comment]
I am sooo sorry.  This was immensely helpful, but I can tell that it took you a while, and it was completely my fault.  

I completely forgot that I had done some of these cards last semester, but took most of the summer off from anki.  I did a mass rescheduling at the end of summer to make all of those cards "new" again, suspended them, and then unsuspended them for learning on 12/2.  Your explanation makes perfect sense with that in mind. 

So again, sorry for wasting your time, but thanks a ton for figuring that out!

Also, I think your idea for having an option to count relearned cards would be perfect for scenarios like this!

**Comment by matthayes** [comment]
No worries; it was pretty quick to figure out.  I'm glad it didn't turn out to be a bug.  There were a couple other reports about issues with 2.1 so I was keen to see if there was a problem.

**Comment by matthayes** [comment]
Closing this.  I opened #23 to create a new graph.
