### ISSUE TITLE
New cards/day not displaying with higher graduating interval

### ISSUE THREAD

**Issue by kq22** [matthayes/anki_progress_stats#9]
As the thread title suggests, when I changed my graduating interval to 3 days from the default 1 day, I noticed I only got "learned cards" counted whenever I pressed the easy button (5 days) to bring them past the graduating interval. Even once I brought a card past its graduating interval by getting it past 3 days, it is not counted towards the "learned cards" graph. 

My settings are as follows:
Steps 1 11 1440 4320
Graduating interval 3 days
Easy interval 5 days

**Comment by matthayes** [comment]
Thanks for the report.  I'll see if I can reproduce this.  By the way, which version of Anki are you using and are you using the old scheduler or the new experimental scheduler?  Also if you're comfortable exporting and sharing your deck it'd make it quicker for me to figure out the problem.  Otherwise I'll have to create a test deck and try this over the next several days.

**Comment by kq22** [comment]
I'm using the most recent version of Anki with the old scheduler. I actually just updated it today, and noticed that I can't export my deck without it crashing, unfortunately.

**Comment by kq22** [comment]
Sorry, I think your addon is probably working as intended, and it's a feature of my graduating intervals that is preventing cards from showing up as learned. Although I'm not sure why it's only showing up as learned cards 5-6 days later as opposed to 3 days later - previously when my graduating interval was 1d, my cards showed up immediately on the learned cards graph

**Comment by matthayes** [comment]
It may have something to do with an interaction between your learning steps and the graduating interval.  Typically I believe that the last learning step is less than the graduating interval.  But in your case the last step 4320 minutes equals the graduating interval of 3.  Anki represents the interval as a negative number representing minutes during learning and a positive number representing days otherwise (supposedly).  The logic handling this in my plugin is [here](https://github.com/matthayes/anki_progress_stats/blob/master/progress_stats/compute.py#L204).  Basically when the interval first goes from negative (learning) to positive (review) it is considered learned.

If you wanted to try debugging this further I would try:

1) Checking the card history by selecting a card in the browser and clicking Info.  This will show you the history of your reviews and the interval for each.  This could give you a clue.
2) Changing the graduating interval from 3 to some greater number like 4, or reducing your last learning step from 4320 to something lower like 2880.

**Comment by matthayes** [comment]
Were you able to get to the bottom of this?

**Comment by matthayes** [comment]
I'll close this for now.  Please reopen if you think there is an issue I should look into.
